version: '3.8'

services:
  # PostgreSQL para desenvolvimento
  postgres-dev:
    image: postgres:16-alpine
    container_name: will-finance-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: will_finance_db
      POSTGRES_USER: will_finance
      POSTGRES_PASSWORD: cyberpunk2077
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - will-finance-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U will_finance -d will_finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para cache (opcional)
  redis-dev:
    image: redis:7-alpine
    container_name: will-finance-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - will-finance-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_dev_data:
    driver: local
    name: will_finance_postgres_dev
  redis_dev_data:
    driver: local
    name: will_finance_redis_dev

networks:
  will-finance-dev:
    driver: bridge
    name: will-finance-dev-network
