version: '3.8'

services:
  db:
    image: mysql:8
    container_name: financeiro_db
    environment:
      MYSQL_DATABASE: financeiro
      MYSQL_USER: financeiro
      MYSQL_PASSWORD: financeiropassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financeiro_backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - uploads:/app/uploads
    depends_on:
      - db
    command: ["npm", "run", "start"] # produção, mais rápido

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financeiro_frontend
    ports:
      - "5173:5173"
    volumes: []
    depends_on:
      - backend
    command: ["npm", "run", "preview"] # serve o build estático

volumes:
  db_data:
  uploads:

