version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: financeiro
      POSTGRES_USER: financeiro
      POSTGRES_PASSWORD: financeiro
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: npm run start:dev
    ports:
      - '3001:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: financeiro
      DATABASE_PASSWORD: financeiro
      DATABASE_NAME: financeiro
    depends_on:
      - db
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /app
    ports:
      - '4000:4000'
    depends_on:
      - backend
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - '8080:80'
    depends_on:
      - backend
volumes:
  pgdata:
